AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/version.rb
    - db/schema.rb
    - "tmp/**/*"
    - Gemfile
    - Guardfile
    - Rakefile
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Exclude:
    - "test/**/*"
    - "db/migrate/20170821181444_devise_create_users.rb"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "test/**/*"
    - "lib/tasks/*.rake"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/LineLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"

Metrics/MethodLength:
  Max: 12
  Exclude:
    - "db/migrate/*"
    - "test/**/*"

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

Rails/Validation:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - "app/controllers/application_controller.rb"
    - "app/helpers/**/*_helper.rb"
    - "app/mailers/**/*_mailer.rb"
    - "app/models/application_record.rb"
    - "config/**/*"
    - "db/**/*"
    - "test/**/*"

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  Exclude:
    - "config/routes.rb"


Style/NumericPredicate:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: verbose

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true

Style/VariableNumber:
  Enabled: false
